channels: [default]
dependencies:
- python=3.7
- lxml
- pillow
- pymongo
- pyodbc
- pytz
- pyyaml
- requests
- shapely
- unidecode
- pip: [bibtexparser, dateparser, inflect, nameparser, requests_cache]
name: minsci
