import argparse
import sys

from minsci.mosaic import Selector
from minsci.mosaic import mosey




def main(args=None):


    class MyParser(argparse.ArgumentParser):
        # From http://stackoverflow.com/questions/4042452
        def error(self, message):
            sys.stderr.write('error: %s\n' % message)
            self.print_help()
            sys.exit(2)




    def mosaic_callback(args):
        args = vars(args)
        mosey(args['path'], jpeg=args['create_jpeg'])




    def selector_callback(args):
        args = vars(args)
        selector = Selector(args['path'])
        params = selector.get_job_settings()
        selector.select(*params)




    if args is None:
        args = sys.argv[1:]

    parser = MyParser(
        description=('Provides access to the mosaic and selector'
                     ' functions from the MinSci Toolkit')
    )
    subparsers = parser.add_subparsers(help='sub-command help')

    # Mosaic subcommand
    mosaic_parser = subparsers.add_parser(
        'mosaic',
        help='Stitch regularly spaced tiles into a mosaic')
    mosaic_parser.add_argument(
        '-p',
        dest = 'path',
        type=str,
        help='the path to the mosaics directory')
    mosaic_parser.add_argument(
        '--create_jpeg',
        action='store_true',
        help='specifies whether to create a JPEG derivative'
             ' from the mosaic')
    mosaic_parser.add_argument(
        '--skipped',
        action='store_true',
        help='the path to a text file containg the indexes of'
             ' skipped files generated by selector')
    mosaic_parser.set_defaults(func=mosaic_callback)

    # Selector subcommand
    selector_parser = subparsers.add_parser(
        'selector',
        help='Select tiles to exclude from an SEM map')
    selector_parser.add_argument(
        '-p',
        dest = 'path',
        type=str,
        help='the path to the mosaics directory')
    selector_parser.set_defaults(func=selector_callback)

    args = parser.parse_args(args)
    args.func(args)




if __name__ == 'main':
    main()
