mp:
  st: saint
  mt: mount
  mtns: mountains
  mtn: mountain
attribute_to_codes:
  - field: mine
    codes:
      - MN
      - MNAU
      - MNC
      - MNCR
      - MNCU
      - MNFE
      - MNN
      - MNQ
      - MNQR
  - field: municipality
    codes:
      - P
  - field: municipality
    codes:
      - L
      - S
  - field: volcano
    codes:
      - CLDA
      - CONE
      - CRTR
      - VLC
  - field: island
    codes:
      - ATOL
      - ISL
      - ISLS
      - ISLET
      - ISLF
      - ISLM
      - ISLT
  - field: county
    codes:
      - ADM2
      - ADM2H
      - ADM3
      - ADM3H
      - ADM4
      - ADM4H
      - ADM5
      - ADM5H
      - ADM6
      - ADM6H
  - field: county
    codes:
      - L
  - field: mining_district
    codes:
      - MNA
  - field: feature
    codes:
      - H
      - L
      - R
      - S
      - T
      - U
      - V
  - field: locality
    codes:
      - A
      - H
      - L
      - P
      - R
      - S
      - T
      - U
      - V
  - field: water_body
    codes:
      - BAY
      - SD
  - field: island_group
    codes:
      - ATOL
      - ISL
      - ISLS
      - ISLET
      - ISLF
      - ISLM
      - ISLT
  - field: state_province
    codes:
      - ADM1
      - ADM1H
      - TERR
  - field: state_province
    codes:
      - L
  - field: country
    codes:
      - PCL
      - PCLD
      - PCLF
      - PCLH
      - PCLI
      - PCLIX
      - PCLS
  - field: continent
    codes:
      - CONT
  - field: country
    codes:
      - CONT
code_to_attribute:
  ADM1: state_province
  ADM2: county
  MN: mine
  PPL: municipality
