ordered:
  - locality
  - mine
  - municipality
  - features
  - volcano
  - water_body
  - island
  - mining_district
  - county
  - state_province
  - country
  - continent
codes:
  locality:
    - A
    - H
    - L
    - P
    - R
    - S
    - T
    - U
    - V
  mine:
    - MN
    - MNAU
    - MNC
    - MNCR
    - MNCU
    - MNFE
    - MNN
    - MNQ
    - MNQR
  municipality:
    - P
  features:
    - A
    - H
    - L
    - P
    - R
    - S
    - T
    - U
    - V
  volcano:
    - CLDA
    - CONE
    - CRTR
    - HLL
    - HLLS
    - MT
    - MTS
    - PK
    - VLC
  maps:
    - _MAP
  island:
    - ATOL
    - ISL
    - ISLET
    - ISLF
    - ISLM
    - ISLT
  mining_district:
    - MNA
  county:
    - ADM2
    - ADM2H
    - ADM3
    - ADM3H
    - ADM4
    - ADM4H
    - ADM5
  water_body:
    - BAY
    - COVE
    - INLT
    - SD
    - GULF
    - H
  island_group:
    - ATOL
    - ISL
    - ISLS
    - ISLET
    - ISLF
    - ISLM
    - ISLT
  state_province:
    - ADM1
    - ADM1H
    - TERR
    - LAND
    - RGN
  country:
    - PCL
    - PCLD
    - PCLF
    - PCLH
    - PCLI
    - PCLIX
    - PCLS
  sea:
    - SEA
    - GULF
  ocean:
    - OCN
  continent:
    - CONT
attribute_to_codes:
  - field: mine
    codes:
      - MN
      - MNAU
      - MNC
      - MNCR
      - MNCU
      - MNFE
      - MNN
      - MNQ
      - MNQR
  - field: feature
    codes:
      - S
      - (1 km)
  - field: municipality
    codes:
      - P
  - field: municipality
    codes:
      - L
      - S
  - field: volcano
    codes:
      - CLDA
      - CONE
      - CRTR
      - VLC
  - field: feature
    codes:
      - (10 km)
  - field: mining_district
    codes:
      - MNA
  - field: island
    codes:
      - ATOL
      - ISL
      - ISLS
      - ISLET
      - ISLF
      - ISLM
      - ISLT
  - field: county
    codes:
      - ADM2
      - ADM2H
      - ADM3
      - ADM3H
      - ADM4
      - ADM4H
      - ADM5
      - ADM5H
      - ADM6
      - ADM6H
  - field: county
    codes:
      - L
  - field: feature
    codes:
      - A
      - H
      - L
      - P
      - R
      - S
      - T
      - U
      - V
  - field: water_body
    codes:
      - BAY
      - SD
  - field: feature
    codes:
      - A
      - H
      - L
      - P
      - R
      - S
      - T
      - U
      - V
  - field: island_group
    codes:
      - ATOL
      - ISL
      - ISLS
      - ISLET
      - ISLF
      - ISLM
      - ISLT
  - field: state_province
    codes:
      - ADM1
      - ADM1H
      - TERR
  - field: state_province
    codes:
      - L
  - field: country
    codes:
      - PCL
      - PCLD
      - PCLF
      - PCLH
      - PCLI
      - PCLIX
      - PCLS
  - field: continent
    codes:
      - CONT
  - field: country
    codes:
      - CONT
code_to_attribute:
  ADM1: state_province
  ADM2: county
  MN: mine
  PPL: municipality
